#!/usr/bin/env node
/*
 * Generates seed.sql from the live catalogue, so the database and the
 * built-in catalogue can never drift apart.
 *
 *   cd web && npm run dev          # in another terminal
 *   node supabase/generate-seed.mjs > supabase/seed.sql
 *
 * Point it elsewhere with GREZZO_URL if the site is already deployed.
 */

const BASE = process.env.GREZZO_URL ?? "http://localhost:3000";
const OPENING_STOCK = Number(process.env.OPENING_STOCK ?? 12);

const q = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`;
const arr = (list) => `ARRAY[${list.map(q).join(", ")}]::text[]`;

const res = await fetch(`${BASE}/api/catalogue`);
if (!res.ok) {
  console.error(`Could not read ${BASE}/api/catalogue (${res.status}). Is the site running?`);
  process.exit(1);
}
const { products } = await res.json();

const out = [];
out.push("-- Generated by supabase/generate-seed.mjs — do not edit by hand.");
out.push(`-- ${products.length} products, generated ${new Date().toISOString()}`);
out.push("");
out.push("begin;");
out.push("");

/* ---- warehouses ---- */
out.push("-- Three sites, chosen so most of India is within three days of one.");
out.push(`insert into warehouses (code, name, city, state, pincode, priority) values
  ('BLR', 'Bengaluru DC', 'Bengaluru', 'Karnataka', '562123', 10),
  ('NCR', 'Delhi NCR DC',  'Gurugram',  'Haryana',   '122505', 20),
  ('BOM', 'Bhiwandi DC',   'Bhiwandi',  'Maharashtra','421302', 30)
on conflict (code) do nothing;`);
out.push("");

out.push("-- Pincode prefix → transit time. Replace with your courier's master.");
out.push(`insert into warehouse_zones (warehouse_code, pincode_prefix, transit_days) values
  ('BLR','5',2), ('BLR','6',3), ('BLR','7',4), ('BLR','4',4), ('BLR','1',6), ('BLR','2',5), ('BLR','3',5), ('BLR','8',5),
  ('NCR','1',2), ('NCR','2',3), ('NCR','3',3), ('NCR','8',4), ('NCR','4',4), ('NCR','5',5), ('NCR','6',6), ('NCR','7',5),
  ('BOM','4',2), ('BOM','3',3), ('BOM','5',3), ('BOM','2',4), ('BOM','1',4), ('BOM','6',5), ('BOM','7',6), ('BOM','8',6)
on conflict do nothing;`);
out.push("");

/* ---- products ---- */
out.push("-- Catalogue");
for (const p of products) {
  out.push(`insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  ${q(p.id)}, ${q(p.slug)}, ${q(p.name)}, ${p.pricePaise}, ${p.comparePaise ?? "null"},
  ${q(p.fit)}, ${q(p.rise)}, ${q(p.wash)}, ${q(p.fabric)}, ${p.weightOz}, ${p.stretchPct},
  ${q(p.collection)}, ${q(p.story)}, ${arr(p.tags)}
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;`);
}
out.push("");

/* ---- variants ---- */
out.push("-- Variants: colour × size. This is the unit stock is held against.");
for (const p of products) {
  const colours = p.colours.map((c) => c.code);
  out.push(`insert into variants (sku, product_id, colour, size)
select ${q(p.id)} || '-' || c || '-' || s, ${q(p.id)}, c, s
from unnest(${arr(colours)}) c
cross join unnest(ARRAY[${p.sizes.join(", ")}]::int[]) s
on conflict (sku) do nothing;`);
}
out.push("");

/* ---- opening stock ---- */
out.push("-- Opening stock, booked in as receipts so the ledger is complete");
out.push("-- from the very first unit rather than starting with a mystery balance.");
out.push(`do $$
declare v record;
begin
  for v in select sku from variants loop
    perform receive_stock(v.sku, 'BLR', ${OPENING_STOCK}, 'opening-balance');
    perform receive_stock(v.sku, 'NCR', ${Math.max(1, Math.round(OPENING_STOCK * 0.6))}, 'opening-balance');
    perform receive_stock(v.sku, 'BOM', ${Math.max(1, Math.round(OPENING_STOCK * 0.6))}, 'opening-balance');
  end loop;
end $$;`);
out.push("");

out.push("-- Empty config row for the admin console to write into.");
out.push(`insert into site_config (key, value) values ('storefront', '{}'::jsonb)
on conflict (key) do nothing;`);
out.push("");
out.push("commit;");
out.push("");

console.log(out.join("\n"));
