-- Generated by supabase/generate-seed.mjs — do not edit by hand.
-- 16 products, generated 2026-08-27T17:21:43.847Z

begin;

-- Three sites, chosen so most of India is within three days of one.
insert into warehouses (code, name, city, state, pincode, priority) values
  ('BLR', 'Bengaluru DC', 'Bengaluru', 'Karnataka', '562123', 10),
  ('NCR', 'Delhi NCR DC',  'Gurugram',  'Haryana',   '122505', 20),
  ('BOM', 'Bhiwandi DC',   'Bhiwandi',  'Maharashtra','421302', 30)
on conflict (code) do nothing;

-- Pincode prefix → transit time. Replace with your courier's master.
insert into warehouse_zones (warehouse_code, pincode_prefix, transit_days) values
  ('BLR','5',2), ('BLR','6',3), ('BLR','7',4), ('BLR','4',4), ('BLR','1',6), ('BLR','2',5), ('BLR','3',5), ('BLR','8',5),
  ('NCR','1',2), ('NCR','2',3), ('NCR','3',3), ('NCR','8',4), ('NCR','4',4), ('NCR','5',5), ('NCR','6',6), ('NCR','7',5),
  ('BOM','4',2), ('BOM','3',3), ('BOM','5',3), ('BOM','2',4), ('BOM','1',4), ('BOM','6',5), ('BOM','7',6), ('BOM','8',6)
on conflict do nothing;

-- Catalogue
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-001', 'selvedge-column-high-rise', 'Selvedge Column', 799000, null,
  'Straight', 'High', 'Raw Indigo', '100% cotton, unsanforised Japanese selvedge', 14.5, 0,
  'Atelier', 'Woven on shuttle looms at 32 picks a minute — a tenth of modern speed. It arrives stiff, and takes about six months to become yours.', ARRAY['selvedge', 'raw', 'japanese', 'heavyweight', 'straight']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-002', 'kyoto-wide-leg', 'Kyoto Wide Leg', 549000, 699000,
  'Wide Leg', 'High', 'Mid Stone', '99% cotton, 1% elastane', 11, 2,
  'Atelier', 'The leg opening is 26cm — deliberately wider than the hip — so the fabric falls in a single unbroken line from waist to floor.', ARRAY['wide', 'high-rise', 'drapey', 'statement']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-003', 'midnight-skinny', 'Midnight Skinny', 399000, null,
  'Skinny', 'Mid', 'Black Overdye', '92% cotton, 6% polyester, 2% elastane', 10, 18,
  'Core', 'Overdyed twice in reactive black so the indigo underneath only shows at the seams, where the thread pulls tight.', ARRAY['skinny', 'black', 'stretch', 'everyday']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-004', 'bleach-cloud-baggy', 'Bleach Cloud Baggy', 629000, null,
  'Baggy', 'High', 'Bleach', '100% cotton', 12.5, 0,
  'Studio', 'Bleached with ozone rather than chlorine — the same result using 95% less water and no discharge into the river.', ARRAY['baggy', 'bleach', 'light', 'oversized', 'sustainable']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-005', 'rinse-straight-classic', 'Rinse Straight', 349000, null,
  'Straight', 'Mid', 'Rinse', '100% cotton', 12, 0,
  'Core', 'One rinse, nothing else. The wash you would get after wearing raw denim home in the rain.', ARRAY['straight', 'classic', 'rinse', 'everyday']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-006', 'atelier-bootcut', 'Atelier Bootcut', 579000, null,
  'Bootcut', 'High', 'Dark Stone', '98% cotton, 2% elastane', 11.5, 5,
  'Atelier', 'Cut narrow through the thigh and released from the knee at exactly 18 degrees — enough to clear a boot, not enough to sweep the floor.', ARRAY['bootcut', 'flare', 'dark', 'tailored']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-007', 'workwear-relaxed-carpenter', 'Workwear Carpenter', 519000, null,
  'Relaxed', 'Mid', 'Mid Stone', '100% cotton duck-faced denim', 13.5, 0,
  'Utility', 'Hammer loop, rule pocket, triple-needle felled seams. Built to the 1930s pattern, which was built to survive a job site.', ARRAY['carpenter', 'relaxed', 'utility', 'workwear', 'heavyweight']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-008', 'ecru-slim-tapered', 'Ecru Slim Taper', 459000, null,
  'Tapered', 'Mid', 'Ecru', '100% undyed cotton', 11, 0,
  'Studio', 'Never dyed at all. What denim looks like before indigo — which is to say, what the cotton actually looks like.', ARRAY['ecru', 'undyed', 'slim', 'taper', 'natural']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-009', 'stonewash-loose', 'Stonewash Loose', 429000, null,
  'Regular', 'High', 'Light Stone', '100% cotton', 12, 0,
  'Core', 'Tumbled with pumice from Icelandic volcanic fields. Each stone lasts about forty washes before it dissolves into sand.', ARRAY['loose', 'stonewash', 'vintage', 'relaxed', '90s']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-010', 'indigo-slim-stretch', 'Indigo Slim Stretch', 379000, null,
  'Slim', 'Mid', 'Dark Stone', '94% cotton, 4% polyester, 2% elastane', 10.5, 22,
  'Core', 'Recovery yarn in the weft means the knee stops bagging by four o''clock. The single most requested fix in denim.', ARRAY['slim', 'stretch', 'dark', 'comfort', 'everyday']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-011', 'painter-wide-ecru', 'Painter Wide', 599000, null,
  'Wide Leg', 'High', 'Ecru', '100% organic cotton', 12.5, 0,
  'Studio', 'Double-knee, dropped crotch, side rule pocket. Modelled on the trousers house painters wore before overalls existed.', ARRAY['painter', 'wide', 'ecru', 'organic', 'utility']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-012', 'raw-skinny-selvedge', 'Raw Skinny Selvedge', 689000, null,
  'Skinny', 'High', 'Raw Indigo', '98% cotton, 2% elastane selvedge', 12.5, 8,
  'Atelier', 'Rare thing: a selvedge denim with give. Woven at half width on a vintage loom, then cut so the red line runs down the outseam.', ARRAY['selvedge', 'raw', 'skinny', 'high-rise', 'premium']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-013', 'loose-tapered', 'Loose Taper', 469000, null,
  'Tapered', 'High', 'Mid Stone', '100% cotton', 11.5, 0,
  'Core', 'Full through the thigh, closed down hard below the knee. The shape that lets a heavy boot sit under a jean without the leg stacking.', ARRAY['taper', 'loose', 'roomy', 'boots']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-014', 'heavy-regular-14oz', 'Heavy Regular 14oz', 559000, null,
  'Regular', 'Mid', 'Rinse', '100% cotton, sanforised', 14, 0,
  'Utility', 'Fourteen ounces per square yard. Heavy enough that the creases behind the knee become permanent — and become a record of how you move.', ARRAY['heavyweight', 'regular', 'rinse', 'durable']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-015', 'bleach-bootcut', 'Bleach Bootcut', 539000, null,
  'Bootcut', 'Mid', 'Bleach', '97% cotton, 3% elastane', 10.5, 12,
  'Studio', 'The flare starts at mid-calf, not the knee, which is what separates a 70s line from a 90s one.', ARRAY['flare', 'bootcut', 'bleach', 'retro', '70s']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;
insert into products (id, slug, name, price_paise, compare_paise, fit, rise, wash, fabric, weight_oz, stretch_pct, collection, story, tags) values (
  'gz-016', 'utility-baggy-cargo', 'Utility Baggy', 649000, null,
  'Baggy', 'Mid', 'Dark Stone', '100% cotton', 13, 0,
  'Utility', 'Two bellowed side pockets set on the seam rather than the front, so they stay flat when empty.', ARRAY['baggy', 'cargo', 'utility', 'dark', 'streetwear']::text[]
) on conflict (id) do update set
  name = excluded.name, price_paise = excluded.price_paise, story = excluded.story;

-- Variants: colour × size. This is the unit stock is held against.
insert into variants (sku, product_id, colour, size)
select 'gz-001' || '-' || c || '-' || s, 'gz-001', c, s
from unnest(ARRAY['raw-indigo', 'rinse', 'black-overdye']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-002' || '-' || c || '-' || s, 'gz-002', c, s
from unnest(ARRAY['mid-stone', 'light-stone', 'dark-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-003' || '-' || c || '-' || s, 'gz-003', c, s
from unnest(ARRAY['black-overdye', 'raw-indigo', 'dark-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-004' || '-' || c || '-' || s, 'gz-004', c, s
from unnest(ARRAY['bleach', 'light-stone', 'ecru']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-005' || '-' || c || '-' || s, 'gz-005', c, s
from unnest(ARRAY['rinse', 'dark-stone', 'raw-indigo']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-006' || '-' || c || '-' || s, 'gz-006', c, s
from unnest(ARRAY['dark-stone', 'mid-stone', 'black-overdye']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-007' || '-' || c || '-' || s, 'gz-007', c, s
from unnest(ARRAY['mid-stone', 'light-stone', 'dark-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-008' || '-' || c || '-' || s, 'gz-008', c, s
from unnest(ARRAY['ecru', 'bleach', 'light-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-009' || '-' || c || '-' || s, 'gz-009', c, s
from unnest(ARRAY['light-stone', 'bleach', 'mid-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-010' || '-' || c || '-' || s, 'gz-010', c, s
from unnest(ARRAY['dark-stone', 'mid-stone', 'black-overdye']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-011' || '-' || c || '-' || s, 'gz-011', c, s
from unnest(ARRAY['ecru', 'bleach', 'light-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-012' || '-' || c || '-' || s, 'gz-012', c, s
from unnest(ARRAY['raw-indigo', 'rinse', 'black-overdye']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-013' || '-' || c || '-' || s, 'gz-013', c, s
from unnest(ARRAY['mid-stone', 'light-stone', 'dark-stone']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-014' || '-' || c || '-' || s, 'gz-014', c, s
from unnest(ARRAY['rinse', 'dark-stone', 'raw-indigo']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-015' || '-' || c || '-' || s, 'gz-015', c, s
from unnest(ARRAY['bleach', 'light-stone', 'ecru']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;
insert into variants (sku, product_id, colour, size)
select 'gz-016' || '-' || c || '-' || s, 'gz-016', c, s
from unnest(ARRAY['dark-stone', 'mid-stone', 'black-overdye']::text[]) c
cross join unnest(ARRAY[28, 30, 31, 32, 33, 34, 36, 38, 40]::int[]) s
on conflict (sku) do nothing;

-- Opening stock, booked in as receipts so the ledger is complete
-- from the very first unit rather than starting with a mystery balance.
do $$
declare v record;
begin
  for v in select sku from variants loop
    perform receive_stock(v.sku, 'BLR', 12, 'opening-balance');
    perform receive_stock(v.sku, 'NCR', 7, 'opening-balance');
    perform receive_stock(v.sku, 'BOM', 7, 'opening-balance');
  end loop;
end $$;

-- Empty config row for the admin console to write into.
insert into site_config (key, value) values ('storefront', '{}'::jsonb)
on conflict (key) do nothing;

commit;

